# vim:tabstop=4:shiftwidth=4:expandtab
services:
    paz:
        image: felixkyun/paz:latest
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - redis
        env_file:
            - .env
    mongo:
        image: mongo:7
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:7

volumes:
    mongo-data:
