# vim:tabstop=4:shiftwidth=4:expandtab
services:
    paz:
        image: felixkyun/paz:latest
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_healthy
        env_file:
            - .env
    mongo:
        image: mongo:7
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db
        healthcheck:
            test:
                [
                    "CMD",
                    "mongosh",
                    "--quiet",
                    "mongodb://localhost:27017/test",
                    "--eval",
                    "db.runCommand({ ping: 1 })",
                ]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s
    redis:
        image: redis:7
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s

volumes:
    mongo-data:
